"""
Seed 55 German bird species into the species table.
Run from repo root:
  cd backend && source .venv/bin/activate
  python -m scripts.seed_birds
"""

import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy import text

from app.models.species import Species

# Photo URLs: Wikimedia Commons Special:FilePath redirects (stable even if file moves)
# Audio URLs: Wikimedia Commons OGG files (sourced from xeno-canto / Macaulay Library)
WC = "https://commons.wikimedia.org/wiki/Special:FilePath/"

BIRDS = [
    {
        "common_name": "House Sparrow",
        "scientific_name": "Passer domesticus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "One of the most widespread birds on Earth, it has lived alongside humans for over 10,000 years.",
        "habitat": "Urban areas, gardens, farmland",
        "behaviour": "Gregarious; forms large flocks, often seen dust-bathing",
        "seasonal_note": "Resident year-round throughout Germany",
        "photos": [
            WC + "Passer_domesticus_male_(15).jpg",
            WC + "Passer_domesticus_female_(8).jpg",
            WC + "House_sparrow04.jpg",
        ],
        "audio_urls": [
            WC + "Passer-domesticus-song.ogg",
            WC + "Passer_domesticus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Blackbird",
        "scientific_name": "Turdus merula",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Males sing the most varied and melodic songs of any European thrush.",
        "habitat": "Gardens, woodland edges, parks",
        "behaviour": "Hops on ground flicking leaves; sings from exposed perches at dusk",
        "seasonal_note": "Resident; northern birds may move south in hard winters",
        "photos": [
            WC + "Turdus_merula_2.jpg",
            WC + "Blackbird_(Turdus_merula)_male,_female_Wikimania_2014.jpg",
            WC + "Turdus_merula_female_2.jpg",
        ],
        "audio_urls": [
            WC + "Turdus_merula_song.ogg",
            WC + "Turdus-merula-mali-aaen.ogg",
        ],
    },
    {
        "common_name": "Great Tit",
        "scientific_name": "Parus major",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Great Tits can recognise individual humans and adjust their alarm calls accordingly.",
        "habitat": "Woodland, gardens, hedgerows",
        "behaviour": "Aggressive at feeders; cracks open nuts by hammering",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Parus_major_Roel_Smeets.jpg",
            WC + "Great_Tit_Parus_major_Kamchatka.jpg",
            WC + "Great_tit_side-on.jpg",
        ],
        "audio_urls": [
            WC + "Parus-major-song.ogg",
            WC + "Parus_major_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Blue Tit",
        "scientific_name": "Cyanistes caeruleus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Famous for learning to open foil milk-bottle tops — a behaviour that spread culturally across Europe.",
        "habitat": "Broadleaved woodland, gardens",
        "behaviour": "Acrobatic; hangs upside down to reach caterpillars on leaf undersides",
        "seasonal_note": "Resident; some irruption movements in autumn",
        "photos": [
            WC + "Cyanistes_caeruleus_-_Blue_tit_in_autumn_2009.jpg",
            WC + "Blue_tit_in_Winthorpe_(8494).jpg",
            WC + "Cyanistes_caeruleus_eating.jpg",
        ],
        "audio_urls": [
            WC + "Cyanistes-caeruleus-song.ogg",
            WC + "Parus_caeruleus_song.ogg",
        ],
    },
    {
        "common_name": "Common Chaffinch",
        "scientific_name": "Fringilla coelebs",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Its Latin name means 'celibate finch' — Linnaeus observed females leaving in winter and males staying behind.",
        "habitat": "Woodland, farmland, gardens",
        "behaviour": "Walks along ground picking up seeds; males sing repetitive descending phrases",
        "seasonal_note": "Resident; large flocks of migrants pass through in October",
        "photos": [
            WC + "Fringilla_coelebs_chaffinch_male_edit2.jpg",
            WC + "Fringilla_coelebs_female_1.jpg",
            WC + "Common_chaffinch_(Fringilla_coelebs_coelebs)_male.jpg",
        ],
        "audio_urls": [
            WC + "Fringilla-coelebs-song.ogg",
            WC + "Fringilla_coelebs_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "European Robin",
        "scientific_name": "Erithacus rubecula",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Robins use Earth's magnetic field to navigate and can 'see' it via quantum effects in their eyes.",
        "habitat": "Woodland, gardens, hedgerows",
        "behaviour": "Fiercely territorial; follows gardeners to catch unearthed worms",
        "seasonal_note": "Resident year-round; sings in winter too",
        "photos": [
            WC + "Robin-withno-worm.jpg",
            WC + "Erithacus_rubecula_with_cocked_head.jpg",
            WC + "Erithacus_rubecula_close.jpg",
        ],
        "audio_urls": [
            WC + "Erithacus_rubecula_song.ogg",
            WC + "Erithacus-rubecula-song.ogg",
        ],
    },
    {
        "common_name": "Common Wood Pigeon",
        "scientific_name": "Columba palumbus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "The largest pigeon in Europe; its five-note coo is one of the most recognisable countryside sounds.",
        "habitat": "Farmland, woodland, urban parks",
        "behaviour": "Grazes in large flocks on crops and acorns",
        "seasonal_note": "Resident; large migratory flocks arrive in autumn from Scandinavia",
        "photos": [
            WC + "Columba_palumbus_2_(Marek_Szczepanek).jpg",
            WC + "Wood_Pigeon_Columba_palumbus.jpg",
            WC + "Columba_palumbus_in_St_James's_Park,_London_-_Nov_2008.jpg",
        ],
        "audio_urls": [
            WC + "Columba-palumbus-song.ogg",
            WC + "Columba_palumbus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Jay",
        "scientific_name": "Garrulus glandarius",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "A single jay can cache up to 5,000 acorns in autumn and remember most locations months later.",
        "habitat": "Deciduous and mixed woodland",
        "behaviour": "Shy and elusive; alarm call a harsh screech",
        "seasonal_note": "Resident; irruptions of northern birds some years",
        "photos": [
            WC + "Garrulus_glandarius_-_Flickr_-_Lip_Kee_(5).jpg",
            WC + "Eurasian_Jay_Garrulus_glandarius.jpg",
            WC + "Jay_-_Garrulus_glandarius.jpg",
        ],
        "audio_urls": [
            WC + "Garrulus-glandarius-alarm.ogg",
            WC + "Garrulus_glandarius_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Magpie",
        "scientific_name": "Pica pica",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Magpies are among the few non-mammal species that can recognise themselves in a mirror.",
        "habitat": "Farmland, woodland edges, gardens",
        "behaviour": "Omnivorous and opportunistic; builds large domed nest of sticks",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Pica_pica_-_Compans_Caffarelli_-_2012-03-16.jpg",
            WC + "Magpie_arp.jpg",
            WC + "Eurasian_Magpie_Pica_pica.jpg",
        ],
        "audio_urls": [
            WC + "Pica-pica-song.ogg",
            WC + "Pica_pica_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Carrion Crow",
        "scientific_name": "Corvus corone",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Crows drop nuts onto roads and wait for cars to crack them open, using pedestrian crossings for safety.",
        "habitat": "Farmland, woodland, urban areas",
        "behaviour": "Highly intelligent; uses tools and plays",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Corvus_corone_-_Crow_-_Corbeau_freux.jpg",
            WC + "Corvus_corone_(Marek_Szczepanek).jpg",
            WC + "Carrion_crow_(Corvus_corone)_3.jpg",
        ],
        "audio_urls": [
            WC + "Corvus-corone-call.ogg",
            WC + "Corvus_corone_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Barn Swallow",
        "scientific_name": "Hirundo rustica",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Travels up to 10,000 km each way between Germany and South Africa every year.",
        "habitat": "Farmland, open country, villages",
        "behaviour": "Aerial insectivore; skims low over water and meadows",
        "seasonal_note": "Summer visitor Apr–Sep; winters in sub-Saharan Africa",
        "photos": [
            WC + "Hirundo_rustica_-_Rasodraza,_Analamanga,_Madagascar-8.jpg",
            WC + "Barn_swallow_(Hirundo_rustica_rustica)_in_flight.jpg",
            WC + "Hirundo_rustica_-_Rasodraza_-_2008-08-02.jpg",
        ],
        "audio_urls": [
            WC + "Hirundo-rustica-song.ogg",
            WC + "Hirundo_rustica_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Swift",
        "scientific_name": "Apus apus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Swifts can remain airborne for up to 10 months continuously, sleeping and mating on the wing.",
        "habitat": "Airspace over towns, villages and open country",
        "behaviour": "Screaming flocks around rooftops in summer evenings",
        "seasonal_note": "Summer visitor May–Aug",
        "photos": [
            WC + "Apus_apus_-_Flickr_-_Lip_Kee_(1).jpg",
            WC + "Common_Swift_(Apus_apus)_in_flight.jpg",
            WC + "Swift_apus_apus.jpg",
        ],
        "audio_urls": [
            WC + "Apus-apus-call.ogg",
            WC + "Apus_apus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "White Stork",
        "scientific_name": "Ciconia ciconia",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "In German folklore the White Stork delivers babies — a tradition tied to its return in spring.",
        "habitat": "Wet meadows, farmland, villages",
        "behaviour": "Nests on rooftops and chimneys; pairs return to same nest each year",
        "seasonal_note": "Summer visitor Mar–Aug; migrates to sub-Saharan Africa",
        "photos": [
            WC + "White_stork_(Ciconia_ciconia)_in_flight.jpg",
            WC + "Weißstorch_Ciconia_ciconia.jpg",
            WC + "Ciconia_ciconia_-_nesting.jpg",
        ],
        "audio_urls": [
            WC + "Ciconia-ciconia-bill-clatter.ogg",
            WC + "Ciconia_ciconia_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Cuckoo",
        "scientific_name": "Cuculus canorus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Each female cuckoo specialises in parasitising one host species and lays eggs that mimic that host's eggs.",
        "habitat": "Woodland edges, heathland, wetlands",
        "behaviour": "Brood parasite; male's call signals spring arrival",
        "seasonal_note": "Summer visitor Apr–Jul",
        "photos": [
            WC + "Cuculus_canorus_vogelartinfo.jpg",
            WC + "Common_Cuckoo_(Cuculus_canorus)_calling.jpg",
            WC + "Cuculus_canorus_in_flight.jpg",
        ],
        "audio_urls": [
            WC + "Cuculus-canorus-call.ogg",
            WC + "Cuculus_canorus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Kingfisher",
        "scientific_name": "Alcedo atthis",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "The Shinkansen bullet train's nose was redesigned after the kingfisher's beak to reduce sonic booms.",
        "habitat": "Clear rivers, streams, lakes",
        "behaviour": "Perches motionless then dives vertically; electric blue flash in flight",
        "seasonal_note": "Resident; disperses to coasts in hard winters",
        "photos": [
            WC + "Alcedo_atthis_-_Riserva_Naturale_di_Confluenza,_Italy_-_8.jpg",
            WC + "Alcedo_atthis_male_-_Riserva_Naturale_di_Confluenza.jpg",
            WC + "Kingfisher-Alcedo-atthis.jpg",
        ],
        "audio_urls": [
            WC + "Alcedo-atthis-call.ogg",
            WC + "Alcedo_atthis_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Hoopoe",
        "scientific_name": "Upupa epops",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "The national bird of Israel; its crest fans open dramatically when alarmed.",
        "habitat": "Open woodland, orchards, vineyards, sandy heaths",
        "behaviour": "Probes soil with long curved bill; undulating butterfly-like flight",
        "seasonal_note": "Rare summer visitor in southern Germany, Apr–Aug",
        "photos": [
            WC + "Upupa_epops_-_Luc_Viatour.jpg",
            WC + "Upupa_epops_02.jpg",
            WC + "Hoopoe_-_Upupa_epops.jpg",
        ],
        "audio_urls": [
            WC + "Upupa-epops-call.ogg",
            WC + "Upupa_epops_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Grey Heron",
        "scientific_name": "Ardea cinerea",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Can stand motionless for hours and strike with lightning speed — the heraldic symbol of patience.",
        "habitat": "Rivers, lakes, fish ponds, wetlands",
        "behaviour": "Solitary hunter; nests colonially in tall trees",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Ardea_cinerea_-_Fishing_(2).jpg",
            WC + "Grey_heron_(Ardea_cinerea)_in_flight.jpg",
            WC + "Ardea_cinerea_standing.jpg",
        ],
        "audio_urls": [
            WC + "Ardea-cinerea-call.ogg",
            WC + "Ardea_cinerea_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Mute Swan",
        "scientific_name": "Cygnus olor",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Despite its name, Mute Swans make a variety of hisses, snorts and wing-beats audible from 1 km.",
        "habitat": "Lakes, rivers, urban ponds",
        "behaviour": "Territorial; arches wings when threatened",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Cygnus_olor_-_Chiemsee_2009.jpg",
            WC + "Mute_swan_Vrhnika.jpg",
            WC + "Mute_swan_(Cygnus_olor)_in_flight.jpg",
        ],
        "audio_urls": [
            WC + "Cygnus-olor-wingbeats.ogg",
            WC + "Cygnus_olor_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Mallard",
        "scientific_name": "Anas platyrhynchos",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "The ancestor of almost all domestic duck breeds except the Muscovy.",
        "habitat": "Ponds, rivers, wetlands, urban parks",
        "behaviour": "Dabbles in shallows; females quack loudly, males make a quiet rasp",
        "seasonal_note": "Resident; northern birds winter in Germany",
        "photos": [
            WC + "Mallard2.jpg",
            WC + "Anas_platyrhynchos_male_female_quadrat.jpg",
            WC + "Mallard_(Anas_platyrhynchos)_female_in_flight.jpg",
        ],
        "audio_urls": [
            WC + "Anas-platyrhynchos-call.ogg",
            WC + "Anas_platyrhynchos_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Teal",
        "scientific_name": "Anas crecca",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Europe's smallest dabbling duck; flocks take off almost vertically in tight formations.",
        "habitat": "Shallow wetlands, coastal marshes",
        "behaviour": "Gregarious and swift in flight",
        "seasonal_note": "Winter visitor Oct–Mar; small breeding population in north Germany",
        "photos": [
            WC + "Anas_crecca_-_Phaleron.jpg",
            WC + "Common_teal_(Anas_crecca)_male_in_eclipse.jpg",
            WC + "Anas_crecca_female.jpg",
        ],
        "audio_urls": [
            WC + "Anas-crecca-call.ogg",
            WC + "Anas_crecca_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Buzzard",
        "scientific_name": "Buteo buteo",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Germany's most common raptor; its mewing call is often used in films as a generic 'eagle' sound.",
        "habitat": "Woodland with open farmland",
        "behaviour": "Soars in thermals; perches on fence posts waiting for prey",
        "seasonal_note": "Resident year-round; augmented by migrants in winter",
        "photos": [
            WC + "Buteo_buteo_-_Raptor_in_flight_(1).jpg",
            WC + "Buteo_buteo_(Common_Buzzard).jpg",
            WC + "Common_Buzzard_Buteo_buteo.jpg",
        ],
        "audio_urls": [
            WC + "Buteo-buteo-call.ogg",
            WC + "Buteo_buteo_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Kestrel",
        "scientific_name": "Falco tinnunculus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Kestrels can see UV light and use it to track vole urine trails invisible to the human eye.",
        "habitat": "Open farmland, motorway verges, urban edges",
        "behaviour": "Hovers facing into wind; dives on small mammals",
        "seasonal_note": "Resident; partial migrant",
        "photos": [
            WC + "Common_kestrel_(Falco_tinnunculus)_male.jpg",
            WC + "Falco_tinnunculus_female_2.jpg",
            WC + "Kestrel_falco_tinnunculus.jpg",
        ],
        "audio_urls": [
            WC + "Falco-tinnunculus-call.ogg",
            WC + "Falco_tinnunculus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Sparrowhawk",
        "scientific_name": "Accipiter nisus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Females are 25% larger than males — one of the greatest size differences of any raptor.",
        "habitat": "Woodland, gardens, hedgerows",
        "behaviour": "Ambush hunter; dashes through vegetation to catch small birds",
        "seasonal_note": "Resident; large passage in autumn along coasts",
        "photos": [
            WC + "Accipiter_nisus_-_male_(1).jpg",
            WC + "Accipiter_nisus_female.jpg",
            WC + "Eurasian_Sparrowhawk_Accipiter_nisus.jpg",
        ],
        "audio_urls": [
            WC + "Accipiter-nisus-call.ogg",
            WC + "Accipiter_nisus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "White-tailed Eagle",
        "scientific_name": "Haliaeetus albicilla",
        "kingdom": "bird",
        "rarity_tier": "rare",
        "conservation_status": "least_concern",
        "fun_fact": "Europe's largest eagle with a wingspan up to 2.4 m — it was reintroduced to Germany after local extinction.",
        "habitat": "Large lakes, rivers, coastal areas",
        "behaviour": "Soars on flat wings; steals fish from Ospreys",
        "seasonal_note": "Resident in NE Germany; more widespread in winter",
        "photos": [
            WC + "Haliaeetus_albicilla_-_Białystok.jpg",
            WC + "White-tailed_eagle_(Haliaeetus_albicilla)_in_flight.jpg",
            WC + "Haliaeetus_albicilla_adult.jpg",
        ],
        "audio_urls": [
            WC + "Haliaeetus-albicilla-call.ogg",
            WC + "Haliaeetus_albicilla_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Osprey",
        "scientific_name": "Pandion haliaetus",
        "kingdom": "bird",
        "rarity_tier": "rare",
        "conservation_status": "least_concern",
        "fun_fact": "The only raptor that plunges feet-first into water; reversible outer toes grip slippery fish.",
        "habitat": "Large clear lakes and rivers",
        "behaviour": "Hovers then plunge-dives; nests on poles and platforms",
        "seasonal_note": "Summer visitor Apr–Sep; expanding breeding range in Germany",
        "photos": [
            WC + "Osprey_Pandion_haliaetus.jpg",
            WC + "Pandion_haliaetus_-_Flickr_-_Lip_Kee.jpg",
            WC + "Osprey_with_fish.jpg",
        ],
        "audio_urls": [
            WC + "Pandion-haliaetus-call.ogg",
            WC + "Pandion_haliaetus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Red Kite",
        "scientific_name": "Milvus milvus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "near_threatened",
        "fun_fact": "Germany holds over 50% of the global Red Kite breeding population.",
        "habitat": "Mixed woodland with open farmland",
        "behaviour": "Graceful forked-tail silhouette; scavenges and soars",
        "seasonal_note": "Resident; large gatherings at winter roosts",
        "photos": [
            WC + "Milvus_milvus_in_flight.jpg",
            WC + "Red_Kite_(Milvus_milvus)_in_flight_(2).jpg",
            WC + "Milvus_milvus_-_forked_tail.jpg",
        ],
        "audio_urls": [
            WC + "Milvus-milvus-call.ogg",
            WC + "Milvus_milvus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Peregrine Falcon",
        "scientific_name": "Falco peregrinus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "The fastest animal on Earth in a stoop — over 320 km/h recorded.",
        "habitat": "Cliffs, tall buildings, quarries",
        "behaviour": "High-speed dive (stoop) to strike prey in mid-air",
        "seasonal_note": "Resident in suitable areas; passage migrants along coasts",
        "photos": [
            WC + "Falco_peregrinus_-_01_(cropped).jpg",
            WC + "Peregrine_falcon_(Falco_peregrinus)_in_flight.jpg",
            WC + "Falco_peregrinus_adult.jpg",
        ],
        "audio_urls": [
            WC + "Falco-peregrinus-call.ogg",
            WC + "Falco_peregrinus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Woodcock",
        "scientific_name": "Scolopax rusticola",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "One of the few birds with 360-degree vision — its eyes are set far back on its skull.",
        "habitat": "Dense deciduous and mixed woodland",
        "behaviour": "Nocturnal; males perform 'roding' display flights at dusk",
        "seasonal_note": "Resident; large influx of migrants in autumn",
        "photos": [
            WC + "Scolopax_rusticola_1.jpg",
            WC + "Woodcock_(Scolopax_rusticola)_camouflage.jpg",
            WC + "Eurasian_Woodcock_Scolopax_rusticola.jpg",
        ],
        "audio_urls": [
            WC + "Scolopax-rusticola-roding.ogg",
            WC + "Scolopax_rusticola_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Curlew",
        "scientific_name": "Numenius arquata",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "near_threatened",
        "fun_fact": "Europe's largest wader; its haunting, bubbling call epitomises wild upland landscapes.",
        "habitat": "Heathland, moorland; estuaries in winter",
        "behaviour": "Long bill probes deep into mud for invertebrates",
        "seasonal_note": "Breeding visitor upland areas; widespread on coasts in winter",
        "photos": [
            WC + "Numenius_arquata_-_Laem_Pak_Bia.jpg",
            WC + "Eurasian_Curlew_(Numenius_arquata)_in_flight.jpg",
            WC + "Numenius_arquata_calling.jpg",
        ],
        "audio_urls": [
            WC + "Numenius-arquata-call.ogg",
            WC + "Numenius_arquata_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Sandpiper",
        "scientific_name": "Actitis hypoleucos",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Bobs its tail constantly — a behaviour whose function scientists still debate.",
        "habitat": "Rocky rivers and lakeshores",
        "behaviour": "Walks with incessant tail-bobbing; low fast flight over water",
        "seasonal_note": "Summer visitor May–Aug; common on passage",
        "photos": [
            WC + "Actitis_hypoleucos_-_Common_Sandpiper.jpg",
            WC + "Common_sandpiper_(Actitis_hypoleucos)_in_flight.jpg",
            WC + "Actitis_hypoleucos_standing.jpg",
        ],
        "audio_urls": [
            WC + "Actitis-hypoleucos-call.ogg",
            WC + "Actitis_hypoleucos_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Black-headed Gull",
        "scientific_name": "Chroicocephalus ridibundus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Its 'black' head is actually dark brown, and it disappears in winter to leave just a dark ear-spot.",
        "habitat": "Lakes, rivers, farmland, coasts",
        "behaviour": "Follows the plough; aggressive mob behaviour at colonies",
        "seasonal_note": "Resident and winter visitor; breeds on inland lakes",
        "photos": [
            WC + "Chroicocephalus_ridibundus_-_Black-headed_Gull.jpg",
            WC + "Black-headed_gull_(Chroicocephalus_ridibundus)_winter.jpg",
            WC + "Larus_ridibundus_in_flight.jpg",
        ],
        "audio_urls": [
            WC + "Chroicocephalus-ridibundus-call.ogg",
            WC + "Larus_ridibundus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Tern",
        "scientific_name": "Sterna hirundo",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Migrates from Germany to Antarctica and back — a round trip of up to 70,000 km a year.",
        "habitat": "Gravel banks, lakes, coasts",
        "behaviour": "Hovers then plunge-dives for small fish",
        "seasonal_note": "Summer visitor May–Sep",
        "photos": [
            WC + "Sterna_hirundo_-_Laem_Pak_Bia.jpg",
            WC + "Common_tern_(Sterna_hirundo)_in_flight.jpg",
            WC + "Sterna_hirundo_with_fish.jpg",
        ],
        "audio_urls": [
            WC + "Sterna-hirundo-call.ogg",
            WC + "Sterna_hirundo_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Tawny Owl",
        "scientific_name": "Strix aluco",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "The classic 'tu-whit tu-whoo' is actually a duet — the female calls 'ke-wick', the male replies 'hooo'.",
        "habitat": "Deciduous woodland, parks, large gardens",
        "behaviour": "Strictly nocturnal; hunts small mammals by sound",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Strix_aluco_-_Tawny_owl.jpg",
            WC + "Tawny_owl_(Strix_aluco)_portrait.jpg",
            WC + "Strix_aluco_standing.jpg",
        ],
        "audio_urls": [
            WC + "Strix-aluco-call.ogg",
            WC + "Strix_aluco_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Long-eared Owl",
        "scientific_name": "Asio otus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Its ear tufts are not ears at all — the actual ears are asymmetrically placed on the skull.",
        "habitat": "Mixed woodland edges, conifer plantations",
        "behaviour": "Roosts communally in winter; hunts over open ground at night",
        "seasonal_note": "Resident; augmented by continental migrants in winter",
        "photos": [
            WC + "Asio_otus_-_Long-eared_Owl.jpg",
            WC + "Long-eared_owl_(Asio_otus)_portrait.jpg",
            WC + "Asio_otus_in_roost.jpg",
        ],
        "audio_urls": [
            WC + "Asio-otus-call.ogg",
            WC + "Asio_otus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Green Woodpecker",
        "scientific_name": "Picus viridis",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Its 'yaffle' laughing call gave it the folk name 'yaffle' in English; it rarely drums on wood.",
        "habitat": "Parkland, woodland edges, orchards",
        "behaviour": "Hammers into ant hills with sticky tongue; bouncy flight",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Picus_viridis_-_European_Green_Woodpecker.jpg",
            WC + "Green_woodpecker_(Picus_viridis)_male.jpg",
            WC + "Picus_viridis_female.jpg",
        ],
        "audio_urls": [
            WC + "Picus-viridis-call.ogg",
            WC + "Picus_viridis_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Great Spotted Woodpecker",
        "scientific_name": "Dendrocopos major",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Drums up to 20 times per second without brain damage — its skull has special shock-absorbing bones.",
        "habitat": "Broadleaved and mixed woodland, parks",
        "behaviour": "Loud drumming in spring; hangs on nut feeders",
        "seasonal_note": "Resident year-round; irruptions of Scandinavian birds some autumns",
        "photos": [
            WC + "Dendrocopos_major_-_Great_Spotted_Woodpecker.jpg",
            WC + "Great_spotted_woodpecker_(Dendrocopos_major)_male.jpg",
            WC + "Dendrocopos_major_female.jpg",
        ],
        "audio_urls": [
            WC + "Dendrocopos-major-drum.ogg",
            WC + "Dendrocopos_major_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Black Woodpecker",
        "scientific_name": "Dryocopus martius",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Europe's largest woodpecker; excavates cavities later used by owls, ducks and bats.",
        "habitat": "Mature beech and pine forest",
        "behaviour": "Crow-sized; loud wailing call; rectangular excavations in trees",
        "seasonal_note": "Resident in suitable forest; expanding westward",
        "photos": [
            WC + "Dryocopus_martius_-_Black_Woodpecker.jpg",
            WC + "Black_woodpecker_(Dryocopus_martius)_male.jpg",
            WC + "Dryocopus_martius_female.jpg",
        ],
        "audio_urls": [
            WC + "Dryocopus-martius-call.ogg",
            WC + "Dryocopus_martius_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Nightingale",
        "scientific_name": "Luscinia megarhynchos",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Sings by day AND night; its nocturnal song is strong enough to drown out traffic noise.",
        "habitat": "Dense scrub, thickets near water, woodland edges",
        "behaviour": "Skulking; song extraordinarily complex and loud for its size",
        "seasonal_note": "Summer visitor Apr–Aug",
        "photos": [
            WC + "Luscinia_megarhynchos_-_Common_Nightingale.jpg",
            WC + "Nightingale_(Luscinia_megarhynchos)_singing.jpg",
            WC + "Luscinia_megarhynchos_portrait.jpg",
        ],
        "audio_urls": [
            WC + "Luscinia-megarhynchos-song.ogg",
            WC + "Luscinia_megarhynchos_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Redstart",
        "scientific_name": "Phoenicurus phoenicurus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "'Redstart' comes from Old English 'steort' (tail) — it constantly quivers its orange-red tail.",
        "habitat": "Open woodland, orchards, parks with old trees",
        "behaviour": "Perches upright and shivers tail; flycatcher habits",
        "seasonal_note": "Summer visitor Apr–Sep",
        "photos": [
            WC + "Phoenicurus_phoenicurus_-_Common_Redstart.jpg",
            WC + "Common_redstart_(Phoenicurus_phoenicurus)_male.jpg",
            WC + "Phoenicurus_phoenicurus_female.jpg",
        ],
        "audio_urls": [
            WC + "Phoenicurus-phoenicurus-song.ogg",
            WC + "Phoenicurus_phoenicurus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Fieldfare",
        "scientific_name": "Turdus pilaris",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Nesting Fieldfares dive-bomb predators and defecate on them — a surprisingly effective deterrent.",
        "habitat": "Farmland, hedgerows, orchards in winter",
        "behaviour": "Flocks strip berry-laden trees; chacking call in flight",
        "seasonal_note": "Winter visitor Oct–Mar; occasional breeder in northern Germany",
        "photos": [
            WC + "Turdus_pilaris_-_Fieldfare.jpg",
            WC + "Fieldfare_(Turdus_pilaris)_in_winter.jpg",
            WC + "Turdus_pilaris_in_flight.jpg",
        ],
        "audio_urls": [
            WC + "Turdus-pilaris-call.ogg",
            WC + "Turdus_pilaris_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Song Thrush",
        "scientific_name": "Turdus philomelos",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "The only bird known to use a 'hammer' — a stone or hard surface — to crack open snail shells.",
        "habitat": "Woodland, gardens, parks",
        "behaviour": "Repeats each phrase two or three times; smashes snails on anvil",
        "seasonal_note": "Resident; northern populations winter further south",
        "photos": [
            WC + "Turdus_philomelos_-_Song_Thrush.jpg",
            WC + "Song_thrush_(Turdus_philomelos)_singing.jpg",
            WC + "Turdus_philomelos_feeding.jpg",
        ],
        "audio_urls": [
            WC + "Turdus-philomelos-song.ogg",
            WC + "Turdus_philomelos_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Goldcrest",
        "scientific_name": "Regulus regulus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Europe's smallest bird at around 5 g; yet it migrates thousands of kilometres across the North Sea.",
        "habitat": "Conifer woodland, mixed forest",
        "behaviour": "Constantly flicks wings; high-pitched 'seee' call",
        "seasonal_note": "Resident; large numbers of migrants arrive in autumn",
        "photos": [
            WC + "Regulus_regulus_-_Goldcrest.jpg",
            WC + "Goldcrest_(Regulus_regulus)_portrait.jpg",
            WC + "Regulus_regulus_in_conifer.jpg",
        ],
        "audio_urls": [
            WC + "Regulus-regulus-song.ogg",
            WC + "Regulus_regulus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Long-tailed Tit",
        "scientific_name": "Aegithalos caudatus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Its domed nest is made of lichen, cobwebs and up to 2,000 feathers — perfectly insulated.",
        "habitat": "Woodland edges, hedgerows, gardens",
        "behaviour": "Moves in noisy flocks; relatives help raise each other's chicks",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Aegithalos_caudatus_-_Long-tailed_Tit.jpg",
            WC + "Long-tailed_tit_(Aegithalos_caudatus)_in_winter.jpg",
            WC + "Aegithalos_caudatus_flock.jpg",
        ],
        "audio_urls": [
            WC + "Aegithalos-caudatus-call.ogg",
            WC + "Aegithalos_caudatus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Nuthatch",
        "scientific_name": "Sitta europaea",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "The only bird that can walk headfirst down a tree trunk — it doesn't need to reverse.",
        "habitat": "Mature deciduous woodland, parkland",
        "behaviour": "Wedges nuts in bark to crack them; plasters nest hole with mud",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Sitta_europaea_-_Eurasian_Nuthatch.jpg",
            WC + "Nuthatch_(Sitta_europaea)_on_branch.jpg",
            WC + "Sitta_europaea_headfirst.jpg",
        ],
        "audio_urls": [
            WC + "Sitta-europaea-call.ogg",
            WC + "Sitta_europaea_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Treecreeper",
        "scientific_name": "Certhia familiaris",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Always spirals upward on tree trunks, then flies to the base of the next tree and starts again.",
        "habitat": "Mature woodland, parkland with large trees",
        "behaviour": "Mouse-like; pressed against bark; thin curved bill",
        "seasonal_note": "Resident year-round",
        "photos": [
            WC + "Certhia_familiaris_-_Common_Treecreeper.jpg",
            WC + "Treecreeper_(Certhia_familiaris)_spiralling.jpg",
            WC + "Certhia_familiaris_bark.jpg",
        ],
        "audio_urls": [
            WC + "Certhia-familiaris-song.ogg",
            WC + "Certhia_familiaris_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Yellowhammer",
        "scientific_name": "Emberiza citrinella",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Beethoven supposedly used its rhythm ('a-little-bit-of-bread-and-no-cheeese') in the Fifth Symphony.",
        "habitat": "Farmland hedgerows, heathland",
        "behaviour": "Males sing from exposed perches; flocks in winter stubble",
        "seasonal_note": "Resident; declining across Germany",
        "photos": [
            WC + "Emberiza_citrinella_-_Yellowhammer.jpg",
            WC + "Yellowhammer_(Emberiza_citrinella)_male.jpg",
            WC + "Emberiza_citrinella_female.jpg",
        ],
        "audio_urls": [
            WC + "Emberiza-citrinella-song.ogg",
            WC + "Emberiza_citrinella_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Reed Bunting",
        "scientific_name": "Emberiza schoeniclus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Now regularly nests in dry arable fields far from its traditional wetland habitat.",
        "habitat": "Reedbeds, wetland margins, increasingly arable",
        "behaviour": "Males flick white outer tail feathers; jangling song",
        "seasonal_note": "Resident; partial migrant; northern birds winter in Germany",
        "photos": [
            WC + "Emberiza_schoeniclus_-_Reed_Bunting.jpg",
            WC + "Reed_bunting_(Emberiza_schoeniclus)_male_breeding.jpg",
            WC + "Emberiza_schoeniclus_female.jpg",
        ],
        "audio_urls": [
            WC + "Emberiza-schoeniclus-song.ogg",
            WC + "Emberiza_schoeniclus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Corn Crake",
        "scientific_name": "Crex crex",
        "kingdom": "bird",
        "rarity_tier": "rare",
        "conservation_status": "least_concern",
        "fun_fact": "Its rasping double call carries over 1 km at night, yet the bird almost never shows itself.",
        "habitat": "Long grass meadows, hayfields",
        "behaviour": "Crepuscular and nocturnal; calls persistently but hides in vegetation",
        "seasonal_note": "Rare summer visitor; populations have crashed due to early mowing",
        "photos": [
            WC + "Crex_crex_-_Corncrake.jpg",
            WC + "Corncrake_(Crex_crex)_in_grass.jpg",
            WC + "Crex_crex_adult.jpg",
        ],
        "audio_urls": [
            WC + "Crex-crex-call.ogg",
            WC + "Crex_crex_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Great Crested Grebe",
        "scientific_name": "Podiceps cristatus",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Their elaborate courtship — the 'weed dance' — was the subject of Julian Huxley's pioneering 1914 study of animal behaviour.",
        "habitat": "Large lakes and reservoirs",
        "behaviour": "Mirror-image courtship displays; chicks ride on parents' backs",
        "seasonal_note": "Resident year-round on larger water bodies",
        "photos": [
            WC + "Podiceps_cristatus_-_Great_Crested_Grebe.jpg",
            WC + "Great_crested_grebe_(Podiceps_cristatus)_courtship.jpg",
            WC + "Podiceps_cristatus_with_chick.jpg",
        ],
        "audio_urls": [
            WC + "Podiceps-cristatus-call.ogg",
            WC + "Podiceps_cristatus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Little Grebe",
        "scientific_name": "Tachybaptus ruficollis",
        "kingdom": "bird",
        "rarity_tier": "common",
        "conservation_status": "least_concern",
        "fun_fact": "Known as 'dabchick' — it dives so swiftly it seems to vanish; nicknamed 'the disappearing act'.",
        "habitat": "Ponds, slow rivers, ditches",
        "behaviour": "Dives frequently; trilling whinny duet in spring",
        "seasonal_note": "Resident; moves to larger waters in hard winters",
        "photos": [
            WC + "Tachybaptus_ruficollis_-_Little_Grebe.jpg",
            WC + "Little_grebe_(Tachybaptus_ruficollis)_breeding.jpg",
            WC + "Tachybaptus_ruficollis_winter.jpg",
        ],
        "audio_urls": [
            WC + "Tachybaptus-ruficollis-call.ogg",
            WC + "Tachybaptus_ruficollis_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Common Crane",
        "scientific_name": "Grus grus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "One of the world's oldest bird species — fossils of closely related cranes date back 10 million years.",
        "habitat": "Wetlands, forests for breeding; open fields on migration",
        "behaviour": "V-formation flocks of thousands pass over Germany in Oct–Nov",
        "seasonal_note": "Passage migrant and winter visitor; small breeding population in NE Germany",
        "photos": [
            WC + "Grus_grus_-_Common_Crane.jpg",
            WC + "Common_crane_(Grus_grus)_in_flight.jpg",
            WC + "Grus_grus_flock_migration.jpg",
        ],
        "audio_urls": [
            WC + "Grus-grus-call.ogg",
            WC + "Grus_grus_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "European Bee-eater",
        "scientific_name": "Merops apiaster",
        "kingdom": "bird",
        "rarity_tier": "rare",
        "conservation_status": "least_concern",
        "fun_fact": "Catches bees and wasps in mid-air, then beats them against a branch to squeeze out the venom.",
        "habitat": "Sandy riverbanks, open country with scattered trees",
        "behaviour": "Colonial nester in sandy slopes; colourful; liquid call",
        "seasonal_note": "Rare breeder in south Germany; expanding northward with climate warming",
        "photos": [
            WC + "Merops_apiaster_-_European_Bee-eater.jpg",
            WC + "European_bee-eater_(Merops_apiaster)_in_flight.jpg",
            WC + "Merops_apiaster_colony.jpg",
        ],
        "audio_urls": [
            WC + "Merops-apiaster-call.ogg",
            WC + "Merops_apiaster_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Little Owl",
        "scientific_name": "Athene noctua",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Sacred to Athena in ancient Greece; its image appeared on Athenian coins.",
        "habitat": "Farmland with old trees, orchards, hedgerows",
        "behaviour": "Active by day; bobs head when curious; barking call",
        "seasonal_note": "Resident year-round; declining due to farmland changes",
        "photos": [
            WC + "Athene_noctua_-_Little_Owl.jpg",
            WC + "Little_owl_(Athene_noctua)_portrait.jpg",
            WC + "Athene_noctua_head_bob.jpg",
        ],
        "audio_urls": [
            WC + "Athene-noctua-call.ogg",
            WC + "Athene_noctua_IBXSCH01.ogg",
        ],
    },
    {
        "common_name": "Eurasian Golden Oriole",
        "scientific_name": "Oriolus oriolus",
        "kingdom": "bird",
        "rarity_tier": "uncommon",
        "conservation_status": "least_concern",
        "fun_fact": "Despite its brilliant yellow plumage, it hides in the canopy so well it is far more often heard than seen.",
        "habitat": "Mature broadleaved woodland, riverside poplars",
        "behaviour": "Fluty whistled song; hammock nest woven between forked twigs",
        "seasonal_note": "Summer visitor May–Aug",
        "photos": [
            WC + "Oriolus_oriolus_-_Golden_Oriole.jpg",
            WC + "Golden_oriole_(Oriolus_oriolus)_male.jpg",
            WC + "Oriolus_oriolus_female.jpg",
        ],
        "audio_urls": [
            WC + "Oriolus-oriolus-song.ogg",
            WC + "Oriolus_oriolus_IBXSCH01.ogg",
        ],
    },
]


async def seed():
    from app.core.config import settings
    url = settings.DATABASE_URL
    engine = create_async_engine(url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    added = 0
    skipped = 0
    async with async_session() as session:
        for bird in BIRDS:
            exists = await session.execute(
                text("SELECT 1 FROM species WHERE scientific_name = :sn"),
                {"sn": bird["scientific_name"]},
            )
            if exists.scalar():
                print(f"  skip  {bird['scientific_name']}")
                skipped += 1
                continue
            session.add(Species(**bird))
            print(f"  add   {bird['scientific_name']}")
            added += 1
        await session.commit()

    await engine.dispose()
    print(f"\nDone — added {added}, skipped {skipped} (already present).")


if __name__ == "__main__":
    asyncio.run(seed())
